### ISSUE TITLE
Laravel 7 Support

### ISSUE THREAD

**Issue by robincsamuel** [codaptive/laravel-pinpoint#3]
Package doesn't support laravel 7

**Comment by robincsamuel** [comment]
My temporary fork can be used while the PR is still open 

https://github.com/robincsamuel/laravel-pinpoint

**Comment by richardnbanks** [comment]
Fixed in by PR #4 and released as v0.0.8.

@robincsamuel Thanks for the work, sorry it took so long to merge.
